#!/usr/bin/env python3
"""gen_icons.py - bake assets/icons/*.png into common/icons.c + icons.h.

Full-color pixel-art icons, hand-drawn (the style: 16/24 px, hard edges,
three-tone shading). Each PNG becomes an icon_t: RGB565
pixels + an 8-bit alpha plane, blended at draw time by render.c's
blit_icon() (which can also scale alpha for dimming/unrevealed states).

Run from anywhere; paths are repo-relative to this file:
    ~/.venvs/pocket-tank/bin/python tools/gen_icons.py
Without Pillow it falls back to its own decoder (8-bit, non-interlaced PNGs,
which is all assets/icons holds).
"""
import os, re, sys, struct, zlib
try:
    from PIL import Image
except ImportError:                     # no Pillow (a bare CI box): a small decoder for our own PNGs
    Image = None


def read_png_rgba(path):
    """8-bit, non-interlaced RGB / RGBA / gray / gray+alpha PNG -> (w, h, [(r,g,b,a)...]).
    The five scanline filters, as the spec has them. Enough for assets/icons;
    anything else says so and asks for Pillow."""
    b = open(path, "rb").read()
    if b[:8] != b"\x89PNG\r\n\x1a\n":
        sys.exit(f"{path}: not a PNG")
    pos, idat, w = 8, b"", None
    while pos < len(b):
        n = struct.unpack(">I", b[pos:pos + 4])[0]
        t, d = b[pos + 4:pos + 8], b[pos + 8:pos + 8 + n]
        pos += 12 + n
        if t == b"IHDR":
            w, h, depth, ctype, _, _, inter = struct.unpack(">IIBBBBB", d)
            if depth != 8 or inter or ctype not in (0, 2, 4, 6):
                sys.exit(f"{path}: {depth}-bit colour type {ctype}{' interlaced' if inter else ''} - install Pillow for this one")
            bpp = {0: 1, 2: 3, 4: 2, 6: 4}[ctype]
        elif t == b"IDAT":
            idat += d
    raw = zlib.decompress(idat)
    stride, prev, px, q = w * bpp, bytearray(w * bpp), [], 0
    for _ in range(h):
        f, line = raw[q], bytearray(raw[q + 1:q + 1 + stride]); q += 1 + stride
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            u = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if f == 1: line[i] = (line[i] + a) & 255
            elif f == 2: line[i] = (line[i] + u) & 255
            elif f == 3: line[i] = (line[i] + ((a + u) >> 1)) & 255
            elif f == 4:
                p = a + u - c; pa, pb, pc = abs(p - a), abs(p - u), abs(p - c)
                line[i] = (line[i] + (a if pa <= pb and pa <= pc else u if pb <= pc else c)) & 255
        for x in range(w):
            v = line[x * bpp:(x + 1) * bpp]
            px.append((v[0], v[0], v[0], 255) if bpp == 1 else (v[0], v[0], v[0], v[1]) if bpp == 2
                      else (v[0], v[1], v[2], 255) if bpp == 3 else tuple(v))
        prev = line
    return w, h, px

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "icons")
OUT_C = os.path.join(ROOT, "common", "icons.c")
OUT_H = os.path.join(ROOT, "common", "icons.h")


def cname(fn):
    stem = os.path.splitext(fn)[0]
    return "icon_" + re.sub(r"[^a-z0-9]+", "_", stem.replace("icon_", "").lower()).strip("_")


def main():
    files = sorted(f for f in os.listdir(SRC) if f.endswith(".png"))
    if not files:
        sys.exit(f"no PNGs in {SRC}")
    decls, defs, table = [], [], []
    total = 0
    for fn in files:
        if Image:
            img = Image.open(os.path.join(SRC, fn)).convert("RGBA")
            w, h = img.size
            px = list(img.getdata())
        else:
            w, h, px = read_png_rgba(os.path.join(SRC, fn))
        if w > 64 or h > 64:
            sys.exit(f"{fn}: {w}x{h} is too big for a UI icon (max 64)")
        rgb, alp = [], []
        for r, g, b, a in px:
            rgb.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))
            alp.append(a)
        n = cname(fn)
        total += w * h * 3
        defs.append(f"static const uint16_t {n}_rgb[{w * h}] = {{\n"
                    + wrap(", ".join(f"0x{v:04x}" for v in rgb)) + "\n};")
        defs.append(f"static const uint8_t {n}_a[{w * h}] = {{\n"
                    + wrap(", ".join(str(v) for v in alp)) + "\n};")
        table.append(f"const icon_t {n} = {{ {w}, {h}, {n}_rgb, {n}_a }};")
        decls.append(f"extern const icon_t {n};")
    hdr = (
        "/* icons.h - GENERATED by tools/gen_icons.py from the assets/icons PNGs.\n"
        " * Do not edit by hand; re-run the script after changing the art. */\n"
        "#ifndef POCKET_TANK_ICONS_H\n#define POCKET_TANK_ICONS_H\n"
        "#include <stdint.h>\n\n"
        "typedef struct { uint8_t w, h; const uint16_t *rgb; const uint8_t *a; } icon_t;\n\n"
        + "\n".join(decls) + "\n\n#endif\n")
    src = (
        "/* icons.c - GENERATED by tools/gen_icons.py from the assets/icons PNGs. */\n"
        '#include "icons.h"\n\n' + "\n\n".join(defs) + "\n\n" + "\n".join(table) + "\n")
    open(OUT_H, "w").write(hdr)
    open(OUT_C, "w").write(src)
    print(f"wrote {len(files)} icons, {total / 1024:.1f} KB of pixel data")
    for f in files:
        print(f"  {cname(f)}")


def wrap(s, width=100):
    out, line = [], "    "
    for tok in s.split(", "):
        if len(line) + len(tok) + 2 > width:
            out.append(line.rstrip())
            line = "    "
        line += tok + ", "
    out.append(line.rstrip().rstrip(","))
    return "\n".join(out)


if __name__ == "__main__":
    main()
